### ISSUE TITLE
Fix error when deleting users with associate accounts

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#198]
** (exit) an exception was raised:
    ** (Ecto.ConstraintError) constraint error when attempting to delete struct:
    * accounts_credit_transactions_account_id_fkey (foreign_key_constraint)
If you would like to stop this constraint violation from raising an
exception and instead add it as an error to your changeset, please
call `foreign_key_constraint/3` on your changeset with the constraint
`:name` as an option.
The changeset has not defined any constraint.
        (ecto 3.8.4) lib/ecto/repo/schema.ex:783: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
        (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
        (ecto 3.8.4) lib/ecto/repo/schema.ex:768: Ecto.Repo.Schema.constraints_to_errors/3
        (ecto 3.8.4) lib/ecto/repo/schema.ex:749: Ecto.Repo.Schema.apply/4
        (ecto 3.8.4) lib/ecto/repo/schema.ex:542: anonymous fn/11 in Ecto.Repo.Schema.do_delete/4
        (keila 0.11.2) lib/keila/admin.ex:30: Keila.Admin.purge_user/1
        (keila 0.11.2) lib/keila_web/controllers/user_admin_controller.ex:45: anonymous fn/1 in KeilaWeb.UserAdminController.delete/2
        (elixir 1.14.3) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2

**Comment by wmnnd** [comment]
I think this was fixed a while ago so I'm closing the issue now.
