### ISSUE TITLE
Internal server error on campaign send via API

### ISSUE THREAD

**Issue by dompie** [pentacent/keila#307]
Hello,

I have a text campaign with sender, tracking and a segment that looks like this one:
![Screenshot 2024-06-25 at 12-32-48 Open Source Newsletter Tool · Keila](https://github.com/pentacent/keila/assets/706491/f90a3240-20bd-4862-8b20-e025bf3cd104)

When I try to send it via swagger API, it looks like sometimes it's not working and I see an internal server error in swagger response:
![Screenshot 2024-06-25 at 12-35-21 Swagger UI](https://github.com/pentacent/keila/assets/706491/003e2208-36f0-4fb0-ac7f-03facf84342c)

In the docker logs I see the following error:
```
keila-1  | 10:27:41.253 request_id=F9w4e5lctX8iY-0AAgrh [info] POST /api/v1/campaigns/nmc_GQL5QWLp/actions/send
keila-1  | 10:27:41.269 [error] #PID<0.15616.0> running KeilaWeb.Endpoint (connection #PID<0.15607.0>, stream id 5) terminated
keila-1  | Server: keila.local:4000 (http)
keila-1  | Request: POST /api/v1/campaigns/nmc_GQL5QWLp/actions/send
keila-1  | ** (exit) an exception was raised:
keila-1  |     ** (Plug.Conn.NotSentError) a response was neither set nor sent from the connection
keila-1  |         (phoenix 1.6.11) lib/phoenix/endpoint/cowboy2_handler.ex:80: Phoenix.Endpoint.Cowboy2Handler.maybe_send/2
keila-1  |         (phoenix 1.6.11) lib/phoenix/endpoint/cowboy2_handler.ex:55: Phoenix.Endpoint.Cowboy2Handler.init/4
keila-1  |         (cowboy 2.10.0) /deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
keila-1  |         (cowboy 2.10.0) /deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
keila-1  |         (cowboy 2.10.0) /deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
keila-1  |         (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

What's the cause for this? Can I fix this with another campaign config or is it some other keila internal stuff?

**Comment by dompie** [comment]
Addition: Although the internal server error happens. The campaign is sent anyway.

**Comment by wmnnd** [comment]
Thank you for reporting this issue! I’ve fixed it now and the fix will be part of the next release.
