### ISSUE TITLE
Blank screen when loading segment

### ISSUE THREAD

**Issue by dompie** [pentacent/keila#309]
Hello,

after editing & saving a segment, it can not be loaded anymore vor viewing/editing. I see only a black/blank screen at the following URL: http://www.domain.com/projects/np_weLJnLY5/segments/nsgm_2yLDZPVb

The keila logs say:
```
keila-1  | 12:19:27.076 [error] #PID<0.22646.0> running KeilaWeb.Endpoint (connection #PID<0.22340.0>, stream id 31) terminated
keila-1  | Server: keila.local:4000 (http)
keila-1  | Request: GET /projects/np_weLJnLY5/segments/nsgm_BzLMnarX
keila-1  | ** (exit) an exception was raised:
keila-1  |     ** (Plug.Conn.NotSentError) a response was neither set nor sent from the connection
keila-1  |         (phoenix 1.6.11) lib/phoenix/endpoint/cowboy2_handler.ex:80: Phoenix.Endpoint.Cowboy2Handler.maybe_send/2
keila-1  |         (phoenix 1.6.11) lib/phoenix/endpoint/cowboy2_handler.ex:55: Phoenix.Endpoint.Cowboy2Handler.init/4
keila-1  |         (cowboy 2.10.0) /deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
keila-1  |         (cowboy 2.10.0) /deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
keila-1  |         (cowboy 2.10.0) /deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
keila-1  |         (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
keila-1  | 12:19:32.281 request_id=F90qU9Wy0gtsm9IAAudh [info] GET /projects/np_weLJnLY5/segments/nsgm_Mvg6QDVZ
keila-1  | 12:19:32.306 [error] #PID<0.22648.0> running KeilaWeb.Endpoint (connection #PID<0.22340.0>, stream id 32) terminated
keila-1  | Server: keila.local:4000 (http)
keila-1  | Request: GET /projects/np_weLJnLY5/segments/nsgm_Mvg6QDVZ
keila-1  | ** (exit) an exception was raised:
keila-1  |     ** (Plug.Conn.NotSentError) a response was neither set nor sent from the connection
keila-1  |         (phoenix 1.6.11) lib/phoenix/endpoint/cowboy2_handler.ex:80: Phoenix.Endpoint.Cowboy2Handler.maybe_send/2
keila-1  |         (phoenix 1.6.11) lib/phoenix/endpoint/cowboy2_handler.ex:55: Phoenix.Endpoint.Cowboy2Handler.init/4
keila-1  |         (cowboy 2.10.0) /deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
keila-1  |         (cowboy 2.10.0) /deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
keila-1  |         (cowboy 2.10.0) /deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
keila-1  |         (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

Please fix, I'd like to delete them.

**Comment by wmnnd** [comment]
That’s a very odd error because it doesn’t really tell where it originated. Is there anything unusual about the segment?

**Comment by dompie** [comment]
I don't know about anything unusual. I tried to reproduce by changing fields to random/empty values, but don't know.

**Comment by wmnnd** [comment]
I’m going to close this because I’m not able to reproduce this issue. If you have more information, feel free to reopen!
