### ISSUE TITLE
Show 404 error instead of 500 when opening unsubscribe link of deleted contact

### ISSUE THREAD

**Issue by almereyda** [pentacent/keila#313]
There were repeating unhandled exceptions in our log, which also didn't surface anywhere near an administrator backend.

```console
14:24:27.655 [error] #PID<0.83010.0> running KeilaWeb.Endpoint (connection #PID<0.81100.0>, stream id 7) terminated
Server: keila.example.com:80 (http)
Request: GET /unsubscribe/np_X4V8agWa/nmr_9xLe8ngB/MTBVV3JlSF
** (exit) an exception was raised:
    ** (Plug.Conn.NotSentError) a response was neither set nor sent from the connection
        (phoenix 1.6.11) lib/phoenix/endpoint/cowboy2_handler.ex:80: Phoenix.Endpoint.Cowboy2Handler.maybe_send/2
        (phoenix 1.6.11) lib/phoenix/endpoint/cowboy2_handler.ex:55: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.10.0) /deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.10.0) /deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.10.0) /deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

These should probably be turned into a proper error message.

**Comment by wmnnd** [comment]
Thank you for reporting this. When a contact no longer exists, this should show a 404 error instead of giving this 500 error.

**Comment by kevinam99** [comment]
Opened a PR for this here https://github.com/pentacent/keila/pull/359

**Comment by kevinam99** [comment]
Oh, this is already fixed to show a 200

**Comment by wmnnd** [comment]
Thanks for confirming it’s working! I’ve removed it from the roadmap now.
