### ISSUE TITLE
Internal Server error when viewing campaign while sending

### ISSUE THREAD

**Issue by dompie** [pentacent/keila#321]
![internal-server-error](https://github.com/user-attachments/assets/56494f40-0311-4f2a-ba64-eb185e6fae4c)

```
09:17:18.221 [error] Postgrex.Protocol (#PID<0.2547.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.189690882.0> timed out because it queued and checked out the connection for longer than 15000ms

#PID<0.189690882.0> was at location:

    :prim_inet.recv0/3
    (postgrex 0.17.1) lib/postgrex/protocol.ex:3188: Postgrex.Protocol.msg_recv/4
    (postgrex 0.17.1) lib/postgrex/protocol.ex:2213: Postgrex.Protocol.recv_bind/3
    (postgrex 0.17.1) lib/postgrex/protocol.ex:2105: Postgrex.Protocol.bind_execute/4
    (db_connection 2.5.0) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
    (db_connection 2.5.0) lib/db_connection.ex:1432: DBConnection.run_execute/5
    (db_connection 2.5.0) lib/db_connection.ex:1527: DBConnection.run/6
    (db_connection 2.5.0) lib/db_connection.ex:713: DBConnection.execute/4

09:17:18.227 request_id=F-TM4K4shkTOHG0qIT5D [info] Sent 500 in 15297ms
09:17:18.228 [error] #PID<0.189690882.0> running KeilaWeb.Endpoint (connection #PID<0.189694997.0>, stream id 1) terminated
Server: newsletter.domain.com:80 (http)
Request: GET /projects/np_BzLMaLXv/campaigns/nmc_xogq6jL2/stats
** (exit) an exception was raised:
    ** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
        (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
        (ecto 3.10.1) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
        (ecto 3.10.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
        (keila 0.14.11) lib/keila/tracking/tracking.ex:201: Keila.Tracking.get_link_stats/1
        (keila 0.14.11) lib/keila_web/live/campaign_stats_live.ex:12: KeilaWeb.CampaignStatsLive.mount/3
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/utils.ex:301: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
        (telemetry 0.4.3) /deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
```

My Keila Version is 0.14.11

**Comment by wmnnd** [comment]
I was unable to reproduce this error, so I will close the issue. Feel free to reopen if you have more information on how to reproduce it.
