### ISSUE TITLE
Error with tzdata-lib

### ISSUE THREAD

**Issue by VincentSC** [pentacent/keila#336]
Got an error just after `[info] Access KeilaWeb.Endpoint at https://....`.

```
app-1      | 12:19:20.855 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Thu, 05 Sep 2024 18:47:42 GMT.
app-1      | 12:19:21.447 [error] GenServer :tzdata_release_updater terminating
app-1      | ** (ArgumentError) errors were found at the given arguments:
app-1      | 
app-1      |   * 2nd argument: not a tuple
app-1      | 
app-1      |     :erlang.element(1, :error)
app-1      |     (tzdata 1.1.1) lib/tzdata/util.ex:223: Tzdata.Util.to_int/1
app-1      |     (tzdata 1.1.1) lib/tzdata/parser.ex:38: Tzdata.Parser.process_rule/1
app-1      |     (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
app-1      |     (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
app-1      |     (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
app-1      |     (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
app-1      |     (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
app-1      | Last message: :check_if_time_to_update
```

Seemingly more projects are hit by this bug. See for example: https://github.com/teslamate-org/teslamate/issues/4196
So maybe just wait and then copy the solution? :)

What I also learned is that some get the error, and some don't, depending on their time-zone. I therefore tried to set the TZ environment variable to "Etc/GMT", but that did not work.

**Comment by wmnnd** [comment]
Thank you for reporting this; this was a bug in `tzdata` and should now be fixed with the update included in Keila 0.15.1.
